const UPDATE_MUSIC_VOLUME = 'UPDATE_MUSIC_VOLUME';
const UPDATE_SOUND_VOLUME = 'UPDATE_SOUND_VOLUME';
const UPDATE_CARDS_AMOUNT = 'UPDATE_CARDS_AMOUNT';
const UPDATE_CARDS_BACK = 'UPDATE_CARDS_BACK';

export {
  UPDATE_MUSIC_VOLUME,
  UPDATE_SOUND_VOLUME,
  UPDATE_CARDS_AMOUNT,
  UPDATE_CARDS_BACK,
};
