export const UPDATE_MUSIC_VOLUME = 'UPDATE_MUSIC_VOLUME';
export const UPDATE_SOUND_VOLUME = 'UPDATE_SOUND_VOLUME';
export const UPDATE_CARDS_BACK = 'UPDATE_CARDS_BACK';
export const UPDATE_CARDS_AMOUNT = 'UPDATE_CARDS_AMOUNT';
export const UPDATE_APP_THEME = 'UPDATE_APP_THEME';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
