const GAME_INIT = 'GAME_INIT';
const GAME_SET_CARDS_AMOUNT = 'GAME_SET_CARDS_AMOUNT';
const GAME_CARD_FLIP_START = 'GAME_CARD_FLIP_START';
const GAME_CARD_FLIP_END = 'GAME_CARD_FLIP_END';
const GAME_CARD_PROCESS = 'GAME_CARD_PROCESS';

export {
  GAME_INIT,
  GAME_SET_CARDS_AMOUNT,
  GAME_CARD_FLIP_START,
  GAME_CARD_FLIP_END,
  GAME_CARD_PROCESS,
};
