export const GAME_INIT = 'GAME_INIT';
export const GAME_UPDATE_TIME = 'GAME_UPDATE_TIME';
export const GAME_RESET = 'GAME_RESET';

export const GAME_TOGGLE_AUTOPLAY = 'GAME_TOGGLE_AUTOPLAY';

export const GAME_CARD_FLIP_START = 'GAME_CARD_FLIP_START';
export const GAME_CARD_FLIP_END = 'GAME_CARD_FLIP_END';
export const GAME_CARD_MATCH_START = 'GAME_CARD_PROCESS_MATCH_START';
export const GAME_CARD_MATCH_END = 'GAME_CARD_MATCH_END';

export const GAME_CLEAR_SOUND = 'GAME_CLEAR_SOUND';
