const GAME_INIT = 'GAME_INIT';
const GAME_UPDATE_TIME = 'GAME_UPDATE_TIME';
const GAME_RESET = 'GAME_RESET';

const GAME_TOGGLE_AUTOPLAY = 'GAME_TOGGLE_AUTOPLAY';

const GAME_CARD_FLIP_START = 'GAME_CARD_FLIP_START';
const GAME_CARD_FLIP_END = 'GAME_CARD_FLIP_END';
const GAME_CARD_MATCH_START = 'GAME_CARD_PROCESS_MATCH_START';
const GAME_CARD_MATCH_END = 'GAME_CARD_MATCH_END';

const GAME_CLEAR_SOUND = 'GAME_CLEAR_SOUND';

export {
  GAME_INIT,
  GAME_UPDATE_TIME,
  GAME_RESET,
  GAME_TOGGLE_AUTOPLAY,
  GAME_CARD_FLIP_START,
  GAME_CARD_FLIP_END,
  GAME_CARD_MATCH_START,
  GAME_CARD_MATCH_END,
  GAME_CLEAR_SOUND,
};
